"""Deduplicate SMILES and average filtered discrete activity levels.

The default input is the workbook generated by ``standardize_mic_level.py``.
All worksheets are processed in workbook order. RDKit canonical isomeric
SMILES are used as compound keys, so equivalent SMILES notations are merged
while distinct stereochemistry remains separate.

Blank Activity Level rows are skipped before SMILES parsing; blank SMILES rows
are also skipped. For two valid measurements, a span of at least 0.6 retains
only the higher value; otherwise both are averaged. For three to eight valid
measurements, repeatedly remove one extreme from the less populated nonempty
side of the current median while the span is at least 0.6. If one side is empty,
remove from the other side. Equal counts remove the extreme farther from the
median, preferring removal of the lower value when distances are equal.
The remaining measurements are averaged. Compounds with more than eight valid
measurements are treated as reference compounds: measurements at least 0.4
below the group maximum are removed before averaging.
"""

from __future__ import annotations

import argparse
import csv
import math
import os
import re
import sys
import tempfile
import unicodedata
from contextlib import contextmanager
from dataclasses import dataclass, field
from decimal import Decimal, InvalidOperation
from pathlib import Path
from threading import Event, Thread
from time import monotonic
from typing import Any, Iterable

try:
    from openpyxl import Workbook, load_workbook
    from openpyxl.utils import get_column_letter
except ImportError:  
    Workbook = None
    load_workbook = None
    get_column_letter = None

try:
    from rdkit import Chem
except ImportError:  
    Chem = None


SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_INPUT_FILE = SCRIPT_DIR / "activity_mic_level.xlsx"
DEFAULT_OUTPUT_FILE = SCRIPT_DIR / "activity_mic_level_mean.xlsx"
DEFAULT_ERROR_LOG_FILE = SCRIPT_DIR / "activity_mic_level_error_log.csv"
DEFAULT_OUTLIER_LOG_FILE = SCRIPT_DIR / "activity_mic_level_outlier_log.csv"

DEFAULT_HEADER_SCAN_ROWS = 50
ORDINARY_ACTIVITY_RANGE_THRESHOLD = Decimal("0.6")
REFERENCE_ACTIVITY_GAP_THRESHOLD = Decimal("0.4")
REFERENCE_COMPOUND_ENTRY_THRESHOLD = 8
ACTIVITY_LEVEL_MIN = 0.0
ACTIVITY_LEVEL_MAX = 1.0
MAX_HEADER_COLUMNS = 256
MAX_XLSX_ROWS = 1_048_576
MAX_DATA_ROWS_PER_SHEET = MAX_XLSX_ROWS - 1

SMILES_HEADER = "SMILES"
ACTIVITY_LEVEL_HEADER = "Activity Level"
OUTPUT_HEADERS = ("Compound ID", "Canonical SMILES", "Mean Activity Level")
OUTLIER_LOG_HEADERS = (
    "Canonical SMILES",
    "Sheet",
    "Row",
    "Activity Level",
    "Minimum Activity Level",
    "Maximum Activity Level",
    "Activity Level Range",
    "Reason",
)


class ProcessingError(Exception):
    """Raised for a controlled input, validation, or output error."""


@dataclass(frozen=True)
class SheetColumns:
    header_row: int
    smiles_column: int
    activity_column: int


@dataclass(frozen=True)
class ActivityObservation:
    activity_level: Decimal
    sheet_name: str
    row_number: int


@dataclass
class CompoundAggregate:
    compound_id: int
    canonical_smiles: str
    occurrence_count: int = 0
    observations: list[ActivityObservation] = field(default_factory=list)
    retained_observations: list[ActivityObservation] = field(default_factory=list)
    discarded: bool = False

    def add_occurrence(
        self,
        observation: ActivityObservation | None,
    ) -> None:
        self.occurrence_count += 1
        if observation is not None:
            self.observations.append(observation)

    @property
    def mean_activity_level(self) -> float | None:
        values = self.retained_observations
        if not values:
            return None
        activity_sum = sum(
            (item.activity_level for item in values),
            Decimal(0),
        )
        return float(activity_sum / len(values))


@dataclass
class RunStats:
    worksheets_processed: int = 0
    rows_scanned: int = 0
    nonempty_smiles_rows: int = 0
    blank_smiles_rows: int = 0
    blank_activity_rows: int = 0
    activity_values_used: int = 0
    activity_values_retained: int = 0
    activity_values_discarded: int = 0
    ordinary_activity_values_discarded: int = 0
    compounds_without_activity_discarded: int = 0
    reference_compounds_preserved: int = 0
    reference_activity_values_discarded: int = 0


def progress_items(items, label: str, total: int | None = None, unit: str = "条"):
    """按完成数量显示进度，不预先读取或复制迭代器内容。"""
    if total is None:
        try:
            total = len(items)
        except TypeError:
            pass
    started = monotonic()
    last_refresh = started
    completed = 0
    previous_width = 0

    def display():
        nonlocal previous_width
        elapsed = monotonic() - started
        if total is None or completed > total:
            progress = f"已处理 {completed} {unit}"
        else:
            fraction = completed / total if total else 1.0
            filled = int(24 * fraction)
            remaining = f"{elapsed / completed * (total - completed):.0f}s" if completed else "--"
            progress = (
                f"[{'#' * filled}{'-' * (24 - filled)}] {fraction:6.1%} "
                f"{completed}/{total} {unit} 剩余约 {remaining}"
            )
        message = f"{label} {progress} 已用 {elapsed:.0f}s"
        print("\r" + message.ljust(previous_width), end="", file=sys.stderr, flush=True)
        previous_width = len(message)

    display()
    try:
        for item in items:
            yield item
            completed += 1
            now = monotonic()
            if now - last_refresh >= 0.25:
                display()
                last_refresh = now
    finally:
        display()
        print(file=sys.stderr, flush=True)


@contextmanager
def timed_stage(label: str):
    """无法取得准确百分比的操作显示动态状态和真实耗时。"""
    started = monotonic()
    stopped = Event()

    def animate():
        index = 0
        while not stopped.wait(0.25):
            symbol = "|/-\\"[index % 4]
            print(
                f"\r[{symbol}] {label}，已用 {monotonic() - started:.0f}s",
                end="", file=sys.stderr, flush=True,
            )
            index += 1

    print(f"[开始] {label}", file=sys.stderr, flush=True)
    worker = Thread(target=animate, daemon=True)
    worker.start()
    status = "中断"
    try:
        yield
        status = "完成"
    finally:
        stopped.set()
        worker.join()
        print(
            f"\r[{status}] {label}，耗时 {monotonic() - started:.1f}s",
            file=sys.stderr, flush=True,
        )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "对标准化 MIC 工作簿中的 SMILES 进行保留立体信息的规范化去重，"
            "两条有效评分跨度达到 0.6 时保留高值，否则取均值；3 至 8 条评分"
            "按当前中位数两侧数量和极端值距离迭代筛除，直到跨度小于 0.6。"
            "超过 8 条有效记录的参考化合物删除"
            "与最高值相差大于或等于 0.4 的低值后计算平均值。"
        )
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT_FILE,
        help=f"输入 XLSX（默认：{DEFAULT_INPUT_FILE.name}）",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_FILE,
        help=f"输出 XLSX（默认：{DEFAULT_OUTPUT_FILE.name}）",
    )
    parser.add_argument(
        "--error-log",
        type=Path,
        default=DEFAULT_ERROR_LOG_FILE,
        help=f"详细错误日志输出文件（默认：{DEFAULT_ERROR_LOG_FILE.name}）",
    )
    parser.add_argument(
        "--outlier-log",
        type=Path,
        default=DEFAULT_OUTLIER_LOG_FILE,
        help=f"不一致化合物筛除日志（默认：{DEFAULT_OUTLIER_LOG_FILE.name}）",
    )
    parser.add_argument(
        "--header-scan-rows",
        type=int,
        default=DEFAULT_HEADER_SCAN_ROWS,
        help=f"每个工作表用于查找表头的最大行数（默认：{DEFAULT_HEADER_SCAN_ROWS}）",
    )
    parser.add_argument(
        "--ignore-errors",
        action="store_true",
        help="输出错误日志后继续生成有效数据的均值文件，而不是遇到错误时直接停止运行",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="显式允许覆盖已存在的输出文件",
    )
    return parser.parse_args()


def normalize_header(value: Any) -> str:
    if value is None:
        return ""
    text = unicodedata.normalize("NFKC", str(value))
    return re.sub(r"\s+", " ", text).strip().casefold()


def row_has_content(row: Iterable[Any]) -> bool:
    return any(value is not None and str(value).strip() for value in row)


def find_sheet_columns(
    worksheet: Any,
    header_scan_rows: int,
) -> tuple[SheetColumns | None, bool]:
    smiles_key = normalize_header(SMILES_HEADER)
    activity_key = normalize_header(ACTIVITY_LEVEL_HEADER)
    scanned_content = False

    for row_number, row in enumerate(
        worksheet.iter_rows(
            min_row=1,
            max_row=header_scan_rows,
            max_col=MAX_HEADER_COLUMNS,
            values_only=True,
        ),
        start=1,
    ):
        if row_has_content(row):
            scanned_content = True

        normalized = [normalize_header(value) for value in row]
        try:
            smiles_column = normalized.index(smiles_key)
            activity_column = normalized.index(activity_key)
        except ValueError:
            continue

        return (
            SheetColumns(
                header_row=row_number,
                smiles_column=smiles_column,
                activity_column=activity_column,
            ),
            scanned_content,
        )

    return None, scanned_content


def canonicalize_smiles(value: Any) -> tuple[str, str]:
    smiles = str(value).strip()
    molecule = Chem.MolFromSmiles(smiles)
    if molecule is None:
        raise ValueError("RDKit 无法解析该 SMILES")

    for atom in molecule.GetAtoms():
        if atom.GetAtomMapNum() != 0:
            atom.SetAtomMapNum(0)

    Chem.AssignStereochemistry(molecule, cleanIt=True, force=True)
    canonical = Chem.MolToSmiles(
        molecule,
        canonical=True,
        isomericSmiles=True,
        kekuleSmiles=False,
    )
    if not canonical:
        raise ValueError("RDKit 未生成有效的规范 SMILES")
    return smiles, canonical


def parse_activity_level(value: Any) -> Decimal | None:
    if value is None:
        return None
    if isinstance(value, str):
        text = unicodedata.normalize("NFKC", value).strip()
        if not text:
            return None
    elif isinstance(value, bool):
        raise ValueError("布尔值不是有效的 Activity Level")
    elif isinstance(value, float) and not math.isfinite(value):
        raise ValueError("Activity Level 必须是有限数值")
    else:
        text = str(value).strip()

    try:
        activity_level = Decimal(text)
    except (InvalidOperation, ValueError) as exc:
        raise ValueError("Activity Level 不是有效数值") from exc
    if not activity_level.is_finite():
        raise ValueError("Activity Level 必须是有限数值")
    if not (
        Decimal(str(ACTIVITY_LEVEL_MIN))
        <= activity_level
        <= Decimal(str(ACTIVITY_LEVEL_MAX))
    ):
        raise ValueError(
            "Activity Level 必须位于闭区间 "
            f"[{ACTIVITY_LEVEL_MIN}, {ACTIVITY_LEVEL_MAX}]"
        )
    return activity_level


def abbreviated_value(value: Any, limit: int = 120) -> str:
    text = str(value).replace("\r", "\\r").replace("\n", "\\n")
    if len(text) > limit:
        text = text[: limit - 3] + "..."
    return repr(text)


def aggregate_workbook(
    input_path: Path,
    header_scan_rows: int,
    error_log_path: Path,
    ignore_errors: bool,
) -> tuple[dict[str, CompoundAggregate], RunStats]:
    with timed_stage(f"打开 Excel：{input_path}"):
        workbook = load_workbook(
            input_path,
            read_only=True,
            data_only=True,
            keep_links=False,
        )
    aggregates: dict[str, CompoundAggregate] = {}
    stats = RunStats()
    errors: list[dict[str, str]] = []

    try:
        for sheet_index, worksheet in enumerate(workbook.worksheets, start=1):
            print(
                f"\n[Sheet {sheet_index}/{len(workbook.worksheets)}] {worksheet.title}",
                file=sys.stderr, flush=True,
            )
            with timed_stage(f"[{worksheet.title}] 查找表头"):
                columns, scanned_content = find_sheet_columns(
                    worksheet,
                    header_scan_rows,
                )
            if columns is None:
                if not scanned_content and worksheet.max_row <= header_scan_rows:
                    print(
                        f"[警告] 跳过空工作表：{worksheet.title}",
                        file=sys.stderr,
                    )
                    continue
                errors.append({
                    "Sheet": worksheet.title,
                    "Location": "N/A",
                    "SMILES": "N/A",
                    "Error": (
                        f"前 {header_scan_rows} 行内未找到 "
                        f"'{SMILES_HEADER}' 和 '{ACTIVITY_LEVEL_HEADER}' 表头"
                    ),
                })
                continue

            stats.worksheets_processed += 1
            max_column = max(
                columns.smiles_column,
                columns.activity_column,
            ) + 1
            total_rows = (
                max(worksheet.max_row - columns.header_row, 0)
                if worksheet.max_row is not None else None
            )
            for row_number, row in progress_items(
                enumerate(
                    worksheet.iter_rows(
                        min_row=columns.header_row + 1,
                        min_col=1,
                        max_col=max_column,
                        values_only=True,
                    ),
                    start=columns.header_row + 1,
                ),
                f"[{worksheet.title}] 读取与SMILES聚合", total_rows, "行",
            ):
                stats.rows_scanned += 1
                activity_value = row[columns.activity_column]
                if activity_value is None or (isinstance(activity_value, str) and not activity_value.strip()):
                    stats.blank_activity_rows += 1
                    continue

                smiles_value = row[columns.smiles_column]
                if smiles_value is None or not str(smiles_value).strip():
                    stats.blank_smiles_rows += 1
                    continue

                stats.nonempty_smiles_rows += 1
                activity_location = f"{get_column_letter(columns.activity_column + 1)}{row_number}"
                
                try:
                    activity_level = parse_activity_level(activity_value)
                except ValueError as exc:
                    errors.append({
                        "Sheet": worksheet.title,
                        "Location": activity_location,
                        "SMILES": str(smiles_value),
                        "Error": f"Activity Level 无效：{exc} (输入值: {abbreviated_value(activity_value)})"
                    })
                    continue

                if activity_level is None:
                    stats.blank_activity_rows += 1
                    continue

                location = f"{get_column_letter(columns.smiles_column + 1)}{row_number}"
                try:
                    _, canonical_smiles = canonicalize_smiles(smiles_value)
                except (TypeError, ValueError, RuntimeError) as exc:
                    errors.append({
                        "Sheet": worksheet.title,
                        "Location": location,
                        "SMILES": str(smiles_value),
                        "Error": f"无法规范化：{exc}"
                    })
                    continue

                aggregate = aggregates.get(canonical_smiles)
                if aggregate is None:
                    aggregate = CompoundAggregate(
                        compound_id=len(aggregates) + 1,
                        canonical_smiles=canonical_smiles,
                    )
                    aggregates[canonical_smiles] = aggregate
                observation = ActivityObservation(
                    activity_level=activity_level,
                    sheet_name=worksheet.title,
                    row_number=row_number,
                )
                aggregate.add_occurrence(observation)
                stats.activity_values_used += 1
    finally:
        workbook.close()

    if errors:
        try:
            with open(error_log_path, mode="w", encoding="utf-8-sig", newline="") as f:
                writer = csv.DictWriter(f, fieldnames=["Sheet", "Location", "SMILES", "Error"])
                writer.writeheader()
                writer.writerows(errors)
            print(f"\n[警告] 发现了 {len(errors)} 个无法解析的数据，已将详细日志保存至：{error_log_path}", file=sys.stderr)
        except Exception as e:
            print(f"[错误] 无法写入错误日志文件：{e}", file=sys.stderr)

        if not ignore_errors:
            raise ProcessingError(
                f"输入数据存在 {len(errors)} 个问题，未生成主输出文件。\n"
                f"请查看 {error_log_path.name} 文件定位并修复问题单元格数据。\n"
                "如需忽略这些错误（将坏数据抛弃）并强制输出有效数据的均值合并文件，请在运行时添加 --ignore-errors 参数。"
            )

    if stats.worksheets_processed == 0:
        raise ProcessingError("输入工作簿中没有可处理的工作表")
    if not aggregates:
        raise ProcessingError("输入工作簿中没有同时具有有效评分和可解析 SMILES 的记录")
    return aggregates, stats


def build_outlier_log_row(
    canonical_smiles: str,
    observation: ActivityObservation,
    minimum_activity: Decimal,
    maximum_activity: Decimal,
    activity_span: Decimal,
    reason: str,
) -> dict[str, Any]:
    return {
        "Canonical SMILES": canonical_smiles,
        "Sheet": observation.sheet_name,
        "Row": observation.row_number,
        "Activity Level": str(observation.activity_level),
        "Minimum Activity Level": str(minimum_activity),
        "Maximum Activity Level": str(maximum_activity),
        "Activity Level Range": str(activity_span),
        "Reason": reason,
    }


def screen_duplicate_activities(
    aggregates: Iterable[CompoundAggregate],
    stats: RunStats,
) -> list[dict[str, Any]]:
    """按有效记录数量筛除不一致评分，再计算保留记录的均值。"""
    outlier_log_rows: list[dict[str, Any]] = []

    for aggregate in progress_items(aggregates, "筛选重复评分并计算均值", unit="个化合物"):
        observations = aggregate.observations
        if not observations:
            retained: list[ActivityObservation] = []
            aggregate.discarded = True
            stats.compounds_without_activity_discarded += 1
        elif len(observations) == 1:
            retained = list(observations)
        elif len(observations) > REFERENCE_COMPOUND_ENTRY_THRESHOLD:
            activity_levels = [item.activity_level for item in observations]
            minimum_activity = min(activity_levels)
            maximum_activity = max(activity_levels)
            activity_span = maximum_activity - minimum_activity
            retained = [
                observation
                for observation in observations
                if maximum_activity - observation.activity_level
                < REFERENCE_ACTIVITY_GAP_THRESHOLD
            ]
            removed = [
                observation
                for observation in observations
                if maximum_activity - observation.activity_level
                >= REFERENCE_ACTIVITY_GAP_THRESHOLD
            ]
            stats.reference_compounds_preserved += 1
            stats.reference_activity_values_discarded += len(removed)
            outlier_log_rows.extend(
                build_outlier_log_row(
                    aggregate.canonical_smiles,
                    observation,
                    minimum_activity,
                    maximum_activity,
                    activity_span,
                    (
                        "参考化合物有效条目超过 8 条；该值比组内最高 "
                        "Activity Level 低至少 0.4，仅删除该记录"
                    ),
                )
                for observation in removed
            )
        else:
            retained = list(observations)
            while len(retained) > 1:
                activity_levels = sorted(item.activity_level for item in retained)
                minimum_activity = activity_levels[0]
                maximum_activity = activity_levels[-1]
                activity_span = maximum_activity - minimum_activity
                if activity_span < ORDINARY_ACTIVITY_RANGE_THRESHOLD:
                    break

                count = len(activity_levels)
                median_activity = (
                    activity_levels[(count - 1) // 2] + activity_levels[count // 2]
                ) / Decimal(2)
                left_count = sum(value < median_activity for value in activity_levels)
                right_count = sum(value > median_activity for value in activity_levels)

                if count == 2:
                    remove_low = True
                    removal_reason = "剩余两条评分跨度达到0.6，保留高值"
                elif left_count == 0:
                    remove_low = False
                    removal_reason = "中位数左侧为空，删除右侧最高值"
                elif right_count == 0:
                    remove_low = True
                    removal_reason = "中位数右侧为空，删除左侧最低值"
                elif left_count != right_count:
                    remove_low = left_count < right_count
                    removal_reason = "删除记录数较少一侧的最外侧值"
                else:
                    remove_low = median_activity - minimum_activity >= maximum_activity - median_activity
                    removal_reason = "两侧数量相同，删除距中位数更远的极端值；等距时删除低值"

                removed_value = minimum_activity if remove_low else maximum_activity
                removal_index = next(
                    index
                    for index, observation in enumerate(retained)
                    if observation.activity_level == removed_value
                )
                removed_observation = retained.pop(removal_index)
                stats.ordinary_activity_values_discarded += 1
                outlier_log_rows.append(
                    build_outlier_log_row(
                        aggregate.canonical_smiles,
                        removed_observation,
                        minimum_activity,
                        maximum_activity,
                        activity_span,
                        (
                            f"普通化合物当前有效条目={count}，跨度≥0.6；"
                            f"中位数={median_activity}，左侧={left_count}，右侧={right_count}；"
                            f"{removal_reason}"
                        ),
                    )
                )

        aggregate.retained_observations = retained
        stats.activity_values_retained += len(retained)
        stats.activity_values_discarded += len(observations) - len(retained)

    return outlier_log_rows


def write_outlier_log(
    output_path: Path,
    rows: Iterable[dict[str, Any]],
) -> None:
    """Atomically write the discarded-activity audit log."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    file_descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{output_path.stem}.",
        suffix=".tmp.csv",
        dir=output_path.parent,
    )
    os.close(file_descriptor)
    temporary_path = Path(temporary_name)
    try:
        with open(
            temporary_path,
            mode="w",
            encoding="utf-8-sig",
            newline="",
        ) as file_handle:
            writer = csv.DictWriter(
                file_handle,
                fieldnames=OUTLIER_LOG_HEADERS,
            )
            writer.writeheader()
            writer.writerows(rows)
        os.replace(temporary_path, output_path)
    except Exception:
        temporary_path.unlink(missing_ok=True)
        raise


def add_output_sheet(workbook: Any, sheet_number: int) -> Any:
    title = "Unique SMILES" if sheet_number == 1 else f"Unique SMILES {sheet_number}"
    worksheet = workbook.create_sheet(title=title)
    worksheet.append(OUTPUT_HEADERS)
    return worksheet


def save_output(
    output_path: Path,
    aggregates: Iterable[CompoundAggregate],
) -> tuple[int, list[int]]:
    workbook = Workbook(write_only=True)
    sheet_number = 1
    worksheet = add_output_sheet(workbook, sheet_number)
    data_rows_in_sheet = 0
    rows_per_sheet: list[int] = []

    for aggregate in progress_items(aggregates, "写入均值结果", unit="个化合物"):
        if aggregate.discarded:
            continue
        if data_rows_in_sheet == MAX_DATA_ROWS_PER_SHEET:
            rows_per_sheet.append(data_rows_in_sheet)
            sheet_number += 1
            worksheet = add_output_sheet(workbook, sheet_number)
            data_rows_in_sheet = 0

        worksheet.append((
            aggregate.compound_id,
            aggregate.canonical_smiles,
            aggregate.mean_activity_level,
        ))
        data_rows_in_sheet += 1

    rows_per_sheet.append(data_rows_in_sheet)

    file_descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{output_path.stem}.",
        suffix=".tmp.xlsx",
        dir=output_path.parent,
    )
    os.close(file_descriptor)
    temporary_path = Path(temporary_name)
    try:
        with timed_stage(f"保存 Excel：{output_path}"):
            workbook.save(temporary_path)
            os.replace(temporary_path, output_path)
    except Exception:
        temporary_path.unlink(missing_ok=True)
        raise
    return sheet_number, rows_per_sheet


def validate_args(args: argparse.Namespace) -> tuple[Path, Path] | None:
    if load_workbook is None or Workbook is None:
        print("[错误] 当前 Python 环境缺少 openpyxl，无法处理 XLSX。", file=sys.stderr)
        return None
    if Chem is None:
        print("[错误] 当前 Python 环境缺少 RDKit，无法进行结构感知的 SMILES 去重。", file=sys.stderr)
        return None
    if args.header_scan_rows < 1:
        print("[错误] --header-scan-rows 必须大于或等于 1。", file=sys.stderr)
        return None

    input_path = args.input.expanduser().resolve()
    output_path = args.output.expanduser().resolve()
    outlier_log_path = args.outlier_log.expanduser().resolve()
    if not input_path.is_file():
        print(f"[错误] 输入文件不存在：{input_path}", file=sys.stderr)
        return None
    if input_path.suffix.casefold() != ".xlsx":
        print(f"[错误] 输入文件必须是 .xlsx：{input_path}", file=sys.stderr)
        return None
    if output_path.suffix.casefold() != ".xlsx":
        print(f"[错误] 输出文件必须是 .xlsx：{output_path}", file=sys.stderr)
        return None
    if outlier_log_path.suffix.casefold() != ".csv":
        print(
            f"[错误] 不一致化合物筛除日志必须是 .csv：{outlier_log_path}",
            file=sys.stderr,
        )
        return None
    if input_path == output_path:
        print("[错误] 输入和输出不能是同一个文件。", file=sys.stderr)
        return None
    if outlier_log_path in {input_path, output_path}:
        print(
            "[错误] 不一致化合物筛除日志不能与输入或主输出使用同一路径。",
            file=sys.stderr,
        )
        return None
    if output_path.exists() and not args.overwrite:
        print(f"[错误] 输出文件已存在：{output_path}\n如需覆盖，请显式添加 --overwrite。", file=sys.stderr)
        return None

    output_path.parent.mkdir(parents=True, exist_ok=True)
    return input_path, output_path


def print_summary(
    input_path: Path,
    output_path: Path,
    outlier_log_path: Path,
    aggregates: dict[str, CompoundAggregate],
    stats: RunStats,
    output_sheet_count: int,
    rows_per_sheet: list[int],
) -> None:
    total_occurrences = sum(item.occurrence_count for item in aggregates.values())
    print(f"\n输入文件：{input_path}")
    print(
        f"处理工作表：{stats.worksheets_processed}；扫描数据行：{stats.rows_scanned}；"
        f"跳过空活性行：{stats.blank_activity_rows}；其余记录中非空 SMILES 行："
        f"{stats.nonempty_smiles_rows}；跳过空 SMILES 行：{stats.blank_smiles_rows}"
    )
    print(
        f"唯一化合物：{len(aggregates)}；合并的重复出现："
        f"{total_occurrences - len(aggregates)}；读取的 Activity Level："
        f"{stats.activity_values_used}；筛选后参与均值："
        f"{stats.activity_values_retained}；筛除的活性记录："
        f"{stats.activity_values_discarded}；参考化合物："
        f"{stats.reference_compounds_preserved}；其中筛除的偏低记录："
        f"{stats.reference_activity_values_discarded}；"
        f"普通化合物迭代筛除的活性记录："
        f"{stats.ordinary_activity_values_discarded}；"
        f"无有效活性而放弃的化合物："
        f"{stats.compounds_without_activity_discarded}"
    )
    print(
        f"输出工作表：{output_sheet_count}；各表数据行："
        + ", ".join(str(count) for count in rows_per_sheet)
    )
    print(f"输出文件：{output_path}")
    print(f"不一致化合物筛除日志：{outlier_log_path}")


def main() -> int:
    args = parse_args()
    paths = validate_args(args)
    if paths is None:
        return 2
    input_path, output_path = paths
    error_log_path = args.error_log.expanduser().resolve()
    outlier_log_path = args.outlier_log.expanduser().resolve()

    try:
        aggregates, stats = aggregate_workbook(
            input_path,
            args.header_scan_rows,
            error_log_path,
            args.ignore_errors,
        )
        outlier_log_rows = screen_duplicate_activities(
            aggregates.values(),
            stats,
        )
        with timed_stage(f"保存筛除日志：{outlier_log_path}"):
            write_outlier_log(outlier_log_path, outlier_log_rows)
        output_sheet_count, rows_per_sheet = save_output(
            output_path,
            aggregates.values(),
        )
    except ProcessingError as exc:
        print(f"\n[错误] {exc}", file=sys.stderr)
        return 1
    except (OSError, ValueError) as exc:
        print(f"\n[错误] 处理失败：{exc}", file=sys.stderr)
        return 1

    print_summary(
        input_path,
        output_path,
        outlier_log_path,
        aggregates,
        stats,
        output_sheet_count,
        rows_per_sheet,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
